version: '3'

services:
  log.service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hello
      - MYSQL_DATABASE=world

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=hello
      - MYSQL_DATABASE=world
